name: image_picker_jv
description: is a package created for the need to implement the Image_picker library whit an interface.
version: 0.0.1
authors: Jeison Manuel Vargas Vargas.

environment:
  sdk: ">=2.6.2 <3.0.0"
  flutter: ">=2.10.5"

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^2.0.0
  image_picker: ^0.8.5
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  : ^3.2.0